# Generated by Django 2.0.6 on 2018-10-15 13:22

from django.db import migrations, models
import utils.other_tools


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_emailverifyrecord'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='status_time',
            field=models.DateTimeField(default=utils.other_tools.avlid_datetiem, verbose_name='有效时间'),
        ),
    ]
