# Generated by Django 2.0.6 on 2018-10-19 17:37

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Multiple_Choice_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='题目')),
                ('degree', models.CharField(choices=[('cj', '初级'), ('zj', '中级'), ('gj', '高级')], max_length=5, verbose_name='考试难度')),
                ('option_0', models.CharField(max_length=200, verbose_name='A')),
                ('option_1', models.CharField(max_length=200, verbose_name='B')),
                ('option_2', models.CharField(max_length=200, verbose_name='C')),
                ('option_3', models.CharField(blank=True, max_length=200, null=True, verbose_name='D')),
                ('option_4', models.CharField(blank=True, max_length=200, null=True, verbose_name='E')),
                ('answer', models.CharField(max_length=4, verbose_name='答案')),
                ('valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
            ],
            options={
                'verbose_name': '多选题',
                'verbose_name_plural': '多选题',
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='名称')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organization.Company', verbose_name='公司')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Department', verbose_name='部门')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.Group', verbose_name='组织')),
            ],
            options={
                'verbose_name': '题库',
                'verbose_name_plural': '题库',
            },
        ),
        migrations.CreateModel(
            name='Single_Choice_Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='题目')),
                ('degree', models.CharField(choices=[('cj', '初级'), ('zj', '中级'), ('gj', '高级')], max_length=5, verbose_name='考试难度')),
                ('option_0', models.CharField(max_length=200, verbose_name='A')),
                ('option_1', models.CharField(max_length=200, verbose_name='B')),
                ('option_2', models.CharField(blank=True, max_length=200, null=True, verbose_name='C')),
                ('option_3', models.CharField(blank=True, max_length=200, null=True, verbose_name='D')),
                ('option_4', models.CharField(blank=True, max_length=200, null=True, verbose_name='E')),
                ('answer', models.CharField(max_length=4, verbose_name='答案')),
                ('valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('questionbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_bank.QuestionBank', verbose_name='题库')),
            ],
            options={
                'verbose_name': '单选题',
                'verbose_name_plural': '单选题',
            },
        ),
        migrations.CreateModel(
            name='True_or_False',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='题目')),
                ('degree', models.CharField(choices=[('cj', '初级'), ('zj', '中级'), ('gj', '高级')], max_length=5, verbose_name='考试难度')),
                ('answer', models.BooleanField(default=True, verbose_name='是否正确（正确打钩）')),
                ('valid', models.BooleanField(default=True, verbose_name='是否有效')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='添加时间')),
                ('questionbank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_bank.QuestionBank', verbose_name='题库')),
            ],
            options={
                'verbose_name': '判断题',
                'verbose_name_plural': '判断题',
            },
        ),
        migrations.AddField(
            model_name='multiple_choice_question',
            name='questionbank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question_bank.QuestionBank', verbose_name='题库'),
        ),
    ]
